-- phpMyAdmin SQL Dump
-- version 4.9.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Feb 27, 2020 at 01:17 PM
-- Server version: 5.7.26
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- --------------------------------------------------------

--
-- Table structure for table `dg_losers`
--

DROP TABLE IF EXISTS `dg_losers`;
CREATE TABLE IF NOT EXISTS `dg_losers` (
  `userid` bigint(20) UNSIGNED NOT NULL COMMENT 'Generated by server',
  `name` varchar(255) DEFAULT NULL COMMENT 'User provided',
  `user_key` varchar(16) DEFAULT NULL COMMENT 'User provided',
  `email` varchar(255) DEFAULT NULL COMMENT 'User provided (opt)',
  `fb_id` varchar(32) DEFAULT NULL COMMENT 'Provided by FB',
  `last_loss` bigint(20) NOT NULL DEFAULT '0' COMMENT 'unix time GMT',
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Truncate table before insert `dg_losers`
--

TRUNCATE TABLE `dg_losers`;
-- --------------------------------------------------------

--
-- Table structure for table `dg_loss_history`
--

DROP TABLE IF EXISTS `dg_loss_history`;
CREATE TABLE IF NOT EXISTS `dg_loss_history` (
  `userid` bigint(20) UNSIGNED NOT NULL,
  `loss_time` bigint(20) UNSIGNED NOT NULL COMMENT 'unix time GMT'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Truncate table before insert `dg_loss_history`
--

TRUNCATE TABLE `dg_loss_history`;
-- --------------------------------------------------------

--
-- Table structure for table `dg_matches`
--

DROP TABLE IF EXISTS `dg_matches`;
CREATE TABLE IF NOT EXISTS `dg_matches` (
  `loser_1` bigint(20) UNSIGNED NOT NULL,
  `loser_2` bigint(20) UNSIGNED NOT NULL,
  UNIQUE KEY `idg_matches` (`loser_1`,`loser_2`) USING BTREE,
  KEY `idg_matches_loser_2` (`loser_2`) USING BTREE,
  KEY `idg_matches_loser_1` (`loser_1`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Truncate table before insert `dg_matches`
--

TRUNCATE TABLE `dg_matches`;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `dg_matches`
--
ALTER TABLE `dg_matches`
  ADD CONSTRAINT `fdg_matches_loser_1` FOREIGN KEY (`loser_1`) REFERENCES `dg_losers` (`userid`) ON DELETE CASCADE,
  ADD CONSTRAINT `fdg_matches_loser_2` FOREIGN KEY (`loser_2`) REFERENCES `dg_losers` (`userid`) ON DELETE CASCADE;
